### ISSUE TITLE
Where's the wiki ?

### ISSUE THREAD

**Issue by unguest** [LavaPower/Sython#1]
Waiting for the wiki before to test it (just not to make my pc crashes ;-) )

**Comment by AlexisHuvier** [comment]
I am writing the wiki on ReadTheDocs and on the repo named "Sython-docs". Thank you for paying attention on this project

**Comment by AlexisHuvier** [comment]
The first version of the wiki is online ! You can read it [here](https://sython-docs.readthedocs.io/fr/latest/index.html). This is in french and there may be spelling mistakes but you can learn how to use Sython.
You can ask other question on discord : LavaPower#1389

**Comment by unguest** [comment]
thanks :)
